### ISSUE TITLE
Nakama ARM build should be published with the same docker version tag

### ISSUE THREAD

**Issue by smsunarto** [heroiclabs/nakama#1222]
It seems like the Nakama ARM images (https://hub.docker.com/r/heroiclabs/nakama/tags) is version tagged separately as `vX.X.X-arm`. This unfortunately makes it difficult to do downstream multi-platform builds as it would require a separate Dockerfile that imports different base image version tags.

The Docker best practice seems to be to publish different platform images under the same version tag and let docker buildx automatically select the correct image based on the platform. By doing it this way, you can do multi-platform builds using a single Dockerfile.

For example:
- [Redis](https://hub.docker.com/layers/library/redis/7.2-bookworm/images/sha256-276dd5763e8a5380d0ce922af362f0cd706f55caef83f8f3eee743552420c692?context=explore) - Notice how a single version tag is used for multiple architectures.

**Comment by toqueteos** [comment]
[Official Docker docs](https://docs.docker.com/build/ci/github-actions/multi-platform/).

It seems easy to accomplish if Docker images are built from GitHub.

If that's not the case it's not that hard anyway, just a single `docker buildx build --platform linux/amd64,linux/arm64 -f ./build/Dockerfile $YOUR_DOCKER_BUILD_PARAMS_HERE` followed by a `docker push $IMAGE_NAME`

Here's a workflow that should do the trick.

It requires two secrets (the Docker hub login credentials)

It publishes a single multi-platform (linux/amd64 and linux/arm64) Docker image when a new release is created:
```yaml
name: docker-images

on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  IMAGE_NAME: "heroiclabs/nakama"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

The only changes required to the repo are as follows:
- Delete both `build/Dockerfile.arm64` and `build/Dockerfile.dsym.arm64`, not needed anymore
- Remove the `GOARCH` line from `build/Dockerfile` and `build/Dockerfile.dsym` as that's no longer required.

If you want to give this a safe try you can modify the metadata step to add a suffix to the generated images like this:

```yaml
      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},suffix=-experimental
```
