### ISSUE TITLE
[Solved] Docker images nakama 2.0.0 cannot start

### ISSUE THREAD

**Issue by gerickt** [heroiclabs/nakama#204]
## Description
Hello friends!,
I have followed the steps described here: https://heroiclabs.com/docs/install-docker-quickstart/
But I can not start the nakama container, the status always marks Restarting.
Cockroach works perfectly, in listening ports 8080 and 26257.

I do not know where to start to see what my mistake is.
Any suggestions?

## Steps to Reproduce

1. Create a file called `docker-compose.yml`
2. Copy the follow content inside
```
version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v2.0.1
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: always
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    image: heroiclabs/nakama:2.0.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257
    restart: always
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
    volumes:
      - ./:/nakama/data
    expose:
      - "7350"
      - "7351"
    ports:
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
```
3. Write to the console: `docker-compose -f docker-compose.yml up`
4. Wait
5. Get the error

## Expected Result
Nakama and Cockroach working
## Actual Result
Nakama error (restarting always)
Cockroach (working fine)
## Context

- [ ] Unity
- [ ] Unreal
- [x ] Other

## Your Environment

- Nakama: 2.0.0
- Cockroach: 2.0.1
- Environment name and version: Docker 18.05.0ce
- Operating System and version: Linux Fedora Server
