### ISSUE TITLE
Migration failing with erroneous error message 

### ISSUE THREAD

**Issue by jvanalstine** [heroiclabs/nakama#722]
I am suddenly hitting a migration error when starting my docker containers:
```
nakama exited with code 1
nakama        | {"level":"info","ts":"2021-11-24T00:36:16.158Z","caller":"migrate/migrate.go:181","msg":"Database connection","dsn":"postgres://root@roach-0:26257/nakama?sslmode=prefer"}
nakama        | {"level":"fatal","ts":"2021-11-24T00:36:16.169Z","caller":"migrate/migrate.go:195","msg":"Failed to check if db exists","db":"nakama","error":"ERROR: relation \"pg_database\" does not exist (SQLSTATE 42P01)"}
```

[This conditional](https://github.com/heroiclabs/nakama/blob/master/migrate/migrate.go#L191) is the line of code seems to be what is failing. I suspect that the if statement was supposed to return true so that `nakamaDBExists = false` is set, but that doesn't seem to happen. Further, I have checked manually that the `pg_database` virtual table exists. It is only the nakama database that is not created.

```
cockroach sql --user=root --insecure --host=localhost:9000 --execute="SELECT EXISTS (SELECT 1 from pg_database WHERE datname = nakama)"
ERROR: column "nakama" does not exist
SQLSTATE: 42703
Failed running "sql"
```

To repro the docker-compose.yml file I am using is the following:
```
version: "3.9"
services:
  roach-0:
    container_name: roach-0
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroach_data_0:/cockroach/cockroach-data
    command: start --insecure --locality=datacenter=vita_net --join=roach-0,roach-1,roach-2
    ports:
      - "9000:26257"
      - "8080:8080"
    networks:
      - vita_net
    hostname: roach-0
  roach-1:
    container_name: roach-1
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroach_data_1:/cockroach/cockroach-data
    command: start --insecure --locality=datacenter=vita_net --join=roach-0,roach-1,roach-2
    networks:
      - vita_net
    hostname: roach-1
  roach-2:
    container_name: roach-2
    image: cockroachdb/cockroach:latest
    volumes:
      - cockroach_data_2:/cockroach/cockroach-data
    command: start --insecure --locality=datacenter=vita_net --join=roach-0,roach-1,roach-2
    networks:
      - vita_net
    hostname: roach-2
  nakama:
    container_name: nakama
    build:
      context: ./
      dockerfile: ./etc/dockerfiles/nakama.Dockerfile #REPLACE ME WITH LOCATION OF BELOW DOCKERFILE
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@roach-0:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@roach-0:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100
    depends_on: 
      - roach-0
      - prometheus
    restart: always
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vita_net
    hostname: nakama
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']
        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'
volumes:
  cockroach_data_0:
  cockroach_data_1:
  cockroach_data_2:
  nakama_data_0:

networks:
  vita_net:
    driver: bridge
```
The nakama dockerfile I am using in the above is this with the module build commented out:
```
FROM heroiclabs/nakama-pluginbuilder:3.9.0 AS builder

ENV GO111MODULE on
ENV CGO_ENABLED 1

WORKDIR /backend

# COPY vita.golang.org/ vita.golang.org/

# RUN cd vita.golang.org && go mod vendor && go build --trimpath --mod=vendor --buildmode=plugin \
#     -o /backend/vita-nakama-module.so ./cmd/nakama-module/main.go

FROM heroiclabs/nakama:3.9.0

COPY --from=builder /backend/vita-nakama-module.so /nakama/data/modules/vita-nakama-module.so
```

After running `docker-compose up -d` run `docker exec -it roach-0 /cockroach/cockroach init --insecure` to init the cluster.
