### ISSUE TITLE
 fatal error: runtime: no plugin module data

### ISSUE THREAD

**Issue by luciancaetano** [heroiclabs/nakama#913]
## Description
This error is thrown when I run golang modules as explained in the documentation

## Steps to Reproduce
####docker-compose.yml
```yml
version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/data

  nakama:
    build: .
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  data:
````
####
Dockerfile
```sh
FROM heroiclabs/nakama-pluginbuilder:3.3.0 AS go-builder

ENV GO111MODULE on
ENV CGO_ENABLED 1

WORKDIR /backend

COPY go.mod .
COPY main.go .
COPY vendor/ vendor/

RUN go build --trimpath --mod=vendor --buildmode=plugin -o ./backend.so

FROM registry.heroiclabs.com/heroiclabs/nakama:3.13.1

COPY --from=go-builder /backend/backend.so /nakama/data/modules/
COPY local.yml /nakama/data/
```

#### go.mod
```go
module myproject.com/mymodule

go 1.19

require (
	github.com/heroiclabs/nakama-common v1.24.0 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)

```
#### main.go
```go
package main

import (
    "context"
    "database/sql"
    "github.com/heroiclabs/nakama-common/runtime"
)

func InitModule(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, initializer runtime.Initializer) error {
    logger.Info("Hello World!")
    return nil
}
```
## Expected Result
Application runs

## Actual Result
```log
 + /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama
 {"level":"info","ts":"2022-09-24T08:16:45.894Z","caller":"migrate/migrate.go:147","msg":"Database connection","dsn":"postgres://postgres:xxxxx@postgres:5432/nakama?sslmode=prefer"}
 {"level":"info","ts":"2022-09-24T08:16:45.913Z","caller":"migrate/migrate.go:195","msg":"Database information","version":"PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit"}
 {"level":"info","ts":"2022-09-24T08:16:45.917Z","caller":"migrate/migrate.go:218","msg":"Successfully applied migration","count":0}
 + exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
 {"level":"info","ts":"2022-09-24T08:16:45.935Z","caller":"server/config.go:86","msg":"Successfully loaded config file","path":"/nakama/data/local.yml"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:306","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.username"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:310","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.password"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:314","msg":"WARNING: insecure default parameter value, change this for production!","param":"console.signing_key"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:318","msg":"WARNING: insecure default parameter value, change this for production!","param":"socket.server_key"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:322","msg":"WARNING: insecure default parameter value, change this for production!","param":"session.encryption_key"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:326","msg":"WARNING: insecure default parameter value, change this for production!","param":"session.refresh_encryption_key"}
 {"level":"warn","ts":"2022-09-24T08:16:45.936Z","caller":"server/config.go:330","msg":"WARNING: insecure default parameter value, change this for production!","param":"runtime.http_key"}
 {"level":"info","ts":"2022-09-24T08:16:45.936Z","caller":"main.go:104","msg":"Nakama starting"}
 {"level":"info","ts":"2022-09-24T08:16:45.936Z","caller":"main.go:105","msg":"Node","name":"nakama","version":"3.13.1+2000e4b8","runtime":"go1.19","cpu":4,"proc":4}
 {"level":"info","ts":"2022-09-24T08:16:45.936Z","caller":"main.go:106","msg":"Data directory","path":"/nakama/data"}
 {"level":"info","ts":"2022-09-24T08:16:45.936Z","caller":"main.go:125","msg":"Database connections","dsns":["postgres:xxxxx@postgres:5432/nakama"]}
 {"level":"debug","ts":"2022-09-24T08:16:45.938Z","caller":"server/db.go:61","msg":"Complete database connection URL","raw_url":"postgres://postgres:localdb@postgres:5432/nakama?sslmode=prefer"}
 {"level":"info","ts":"2022-09-24T08:16:45.944Z","caller":"main.go:131","msg":"Database information","version":"PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit"}
 {"level":"info","ts":"2022-09-24T08:16:45.949Z","caller":"server/leaderboard_rank_cache.go:117","msg":"Initializing leaderboard rank cache"}
 {"level":"info","ts":"2022-09-24T08:16:45.949Z","caller":"server/runtime.go:587","msg":"Initialising runtime","path":"/nakama/data/modules"}
 {"level":"info","ts":"2022-09-24T08:16:45.949Z","caller":"server/runtime.go:594","msg":"Initialising runtime event queue processor"}
 {"level":"info","ts":"2022-09-24T08:16:45.950Z","caller":"server/runtime.go:596","msg":"Runtime event queue processor started","size":65536,"workers":8}
 {"level":"info","ts":"2022-09-24T08:16:45.950Z","caller":"server/runtime_go.go:2516","msg":"Initialising Go runtime provider","path":"/nakama/data/modules"}
 {"level":"info","ts":"2022-09-24T08:16:45.949Z","caller":"server/leaderboard_rank_cache.go:240","msg":"Leaderboard rank cache initialization completed successfully","cached":[],"skipped":[]}
 fatal error: runtime: no plugin module data

 goroutine 1 [running]:
 runtime.throw({0x1ca3773?, 0xa83cdb?})
      runtime/panic.go:1047 +0x5d fp=0xc00051fd58 sp=0xc00051fd28 pc=0xa533fd
 plugin.lastmoduleinit()
      runtime/plugin.go:20 +0x8ce fp=0xc00051fe40 sp=0xc00051fd58 pc=0xa83b2e
 plugin.open({0xc000486140, 0x1f})
      plugin/plugin_dlopen.go:77 +0x3ef fp=0xc0005200b0 sp=0xc00051fe40 pc=0x135a06f
 plugin.Open(...)
      plugin/plugin.go:32
 github.com/heroiclabs/nakama/v3/server.openGoModule(0xc00048615c?, {0xc000496048?, 0x0?}, {0xc000486140, 0x1f})
      github.com/heroiclabs/nakama/v3/server/runtime_go.go:2610 +0x13b fp=0xc0005202c0 sp=0xc0005200b0 pc=0x178917b
 github.com/heroiclabs/nakama/v3/server.NewRuntimeProviderGo({_, _}, _, _, _, _, {_, _}, _, {0x2283a00, ...}, ...)
      github.com/heroiclabs/nakama/v3/server/runtime_go.go:2526 +0xd25 fp=0xc0005205c8 sp=0xc0005202c0 pc=0x1787ae5
 github.com/heroiclabs/nakama/v3/server.NewRuntime({0x2277080, 0xc0004923c0}, 0xc000480060?, 0xc000480060?, 0xc00049ac30?, 0x2b93740?, 0x2d9e9c0?, {0x22870f8?, _}, 0xc0004681e0, ...)
      github.com/heroiclabs/nakama/v3/server/runtime.go:600 +0x656 fp=0xc0005296e8 sp=0xc0005205c8 pc=0x17323d6
 main.main()
      main.go:156 +0x161c fp=0xc000529f80 sp=0xc0005296e8 pc=0x1951cbc
 runtime.main()
      runtime/proc.go:250 +0x212 fp=0xc000529fe0 sp=0xc000529f80 pc=0xa55f72
 runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc000529fe8 sp=0xc000529fe0 pc=0xa88f81

 goroutine 2 [force gc (idle)]:
 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
      runtime/proc.go:363 +0xd6 fp=0xc00005efb0 sp=0xc00005ef90 pc=0xa56336
 runtime.goparkunlock(...)
      runtime/proc.go:369
 runtime.forcegchelper()
      runtime/proc.go:302 +0xad fp=0xc00005efe0 sp=0xc00005efb0 pc=0xa561cd
 runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0xa88f81
 created by runtime.init.6
      runtime/proc.go:290 +0x25

 goroutine 3 [GC sweep wait]:
 runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
      runtime/proc.go:363 +0xd6 fp=0xc00005f790 sp=0xc00005f770 pc=0xa56336
 runtime.goparkunlock(...)
      runtime/proc.go:369
 runtime.bgsweep(0x0?)
      runtime/mgcsweep.go:297 +0xd7 fp=0xc00005f7c8 sp=0xc00005f790 pc=0xa3f277
 runtime.gcenable.func1()
      runtime/mgc.go:178 +0x26 fp=0xc00005f7e0 sp=0xc00005f7c8 pc=0xa33e06
 runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0xa88f81
 created by runtime.gcenable
      runtime/mgc.go:178 +0x6b

 goroutine 4 [GC scavenge wait]:
 runtime.gopark(0xc00007e000?, 0x225ff10?, 0x0?, 0x0?, 0x0?)
      runtime/proc.go:363 +0xd6 fp=0xc00005ff70 sp=0xc00005ff50 pc=0xa56336
 runtime.goparkunlock(...)
      runtime/proc.go:369
 runtime.(*scavengerState).park(0x2da4ec0)
      runtime/mgcscavenge.go:389 +0x53 fp=0xc00005ffa0 sp=0xc00005ff70 pc=0xa3d253
 runtime.bgscavenge(0x0?)
      runtime/mgcscavenge.go:622 +0x65 fp=0xc00005ffc8 sp=0xc00005ffa0 pc=0xa3d865
 runtime.gcenable.func2()
      runtime/mgc.go:179 +0x26 fp=0xc00005ffe0 sp=0xc00005ffc8 pc=0xa33da6
 runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0xa88f81
 created by runtime.gcenable
      runtime/mgc.go:179 +0xaa
```

## Your Environment
- Nakama: 3.13.1
- Database: postgres:12.2-alpine
- Operating System and version: Docker Desktop 4.12.0(85629)
