### ISSUE TITLE
Can’t change default login and password for Nakama Console

### ISSUE THREAD

**Issue by NoizlessDog** [heroiclabs/nakama#921]
1. Versions: Nakama {3.13.1+2000e4b8}, {Docker Compose}
2. Hello everyone. I'm the new one of Nakama user. My Nakama Server is working. I could connect to the Nakama Console but I couldn't change default login and password for it.

This is my docker-compose.yml
```
...
  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.13.1
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          /nakama/nakama --config /nakama/data/config.yml  
    restart: "always"
    links:
      - "cockroachdb:db"
    depends_on:
      cockroachdb:
        condition: service_healthy
      prometheus:
        condition: service_started
    volumes:
      - ./data:/nakama/data
...

```

This is my config.yml in data folder
```
...
 name: nakama-node-1
data_dir: "./data/"

logger:
    stdout: false
    level: "warn"
    file: "/nakama/data/logfile.log"

console:
    port: 7351
    username: "********"
    password: "*************"
...

```

"Admin" and "password" still work to entering in Nakama console.
Can somebody help me with it?
