### ISSUE TITLE
can not connect to database after running for some time

### ISSUE THREAD

**Issue by kennir** [heroiclabs/nakama#975]
Before you submit an issue we recommend you drop into the [community forum](https://forum.heroiclabs.com) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

## Description

I run a Nakama server by docker on AWS, I encountered an error that failed to connect to the database after running for some time

My docker compose file
```
version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v20.2
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.15.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama --config /nakama/data/my-config.yaml
    restart: "always"
    links:
      - "cockroachdb:db"
    depends_on:
      cockroachdb:
        condition: service_healthy
      prometheus:
        condition: service_started
    volumes:
      - ./data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'      
    ports:
      - '9090:9090'
volumes:
  data:
```

## Steps to Reproduce

`docker-compose up -d` start server, wait a few days, the error occurred

I got the log below 
```
{"level":"error","ts":"2023-01-16T15:57:02.886Z","caller":"server/console.go:346","msg":"Error querying storage collections.","error":"failed to connect to `host=cockroachdb user=root database=nakama`: hostname resolving error (lookup cockroachdb on 127.0.0.11:53: no such host)"}
```

## Expected Result

the Nakama server can connect to database

## Actual Result

the Nakama server can not connect to database

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 3.15.0
- Database: cockroachdb/cockroach:latest-v20.2
- Environment name and version:  Docker version 20.10.21, build baeda1f
- Operating System and version: Amazon Linux amzn2-ami-kernel-5.10-hvm-2.0.20221103.3-x86_64-gp2
